# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - master
      - next
      - beta
      - release/*
  pull_request:
    branches:
      - master
      - next
      - beta
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --frozen-lockfile
    - run: yarn test

