# This is a basic workflow to help you get started with Actions

name: CI

on:
 - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node_modules
      uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    
    - name: Unit Test
      run: yarn test
      
    - name: Build 
      run: yarn build
    
    - name: Upload 'lib' artifact
      uses: actions/upload-artifact@v1
      with:
        name: lib
        path: lib

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node: [ '6', '8', '10', '12' ]
    name: Integration Test on Node ${{ matrix.node }}
    steps:
    - name: Download lib
      uses: actions/download-artifact@v1
      with:
        name: lib
        
    - run: ls lib
