# Release to NPM via semantic-release when pushed to protected branch.

name: Release

on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - run: yarn install

      - name: Build
        run: yarn build

      - name: Upload 'lib' artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - run: yarn install

      - name: Download lib
        uses: actions/download-artifact@v2
        with:
          name: lib

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
