# Build and test when pull request is made to protected branches.
# This workflow will run integration tests against multiple versions of Node.

name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - next
      - beta
      - alpha
      - release/*

jobs:
  lint:
    strategy:
      matrix:
        node: ['10', '12', '14', '16']
    name: Lint on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

  test:
    strategy:
      matrix:
        node: ['10', '12', '14', '16']
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: yarn test

  build:
    strategy:
      matrix:
        node: ['10', '12', '14', '16']
    name: Build on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: yarn build

      - name: Upload 'lib' artifact
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: lib
