# Build and test when pull request is made to protected branches.
# This workflow will run integration tests against multiple versions of Node.

name: CI

on:
  pull_request:
    branches:
      - master
      - next
      - beta
      - alpha
      - release/*

jobs:
  lint:
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Lint on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn install

      - name: Lint
        run: yarn lint

  test:
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn install

      - name: Test
        run: yarn test

  build:
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Build on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn install

      - name: Build
        run: yarn build
